# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oper_on_terr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResqueTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('resque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_api.ResqueTeam')),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square', models.IntegerField()),
                ('coor_start', models.CharField(max_length=15)),
                ('coor_end', models.CharField(max_length=15)),
                ('operators', models.ManyToManyField(through='test_api.Oper_on_terr', to='test_api.Operator')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_api.Sensor')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_operators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_api.Operator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_api.User')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='operators',
            field=models.ManyToManyField(through='test_api.User_operators', to='test_api.Operator'),
        ),
        migrations.AddField(
            model_name='oper_on_terr',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_api.Operator'),
        ),
        migrations.AddField(
            model_name='oper_on_terr',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_api.Territory'),
        ),
    ]
